### ISSUE TITLE
TaskCanceledException when in-process hosting is enabled

### ISSUE THREAD

**Issue by jussimattila** [damianh/ProxyKit#60] opened 2019-02-06 08:16 UTC
Hi! I'm investigating ProxyKit for a new project. Everything looks really great but I have not been able to solve one development time issue. Do you know why connecting to hot-module-replacement (HMR) endpoint fails over ProxyKit. Here's the exception from debug output:
```
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/2.0 GET https://localhost:44317/dist/__webpack_hmr  
System.Net.Http.HttpClient.ProxyKitClient.LogicalHandler:Information: Start processing HTTP request GET http://localhost:54469/dist/__webpack_hmr
System.Net.Http.HttpClient.ProxyKitClient.ClientHandler:Information: Sending HTTP request GET http://localhost:54469/dist/__webpack_hmr
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:54469/dist/__webpack_hmr  
System.Net.Http.HttpClient.ProxyKitClient.ClientHandler:Information: Received HTTP response after 57.6952ms - OK
System.Net.Http.HttpClient.ProxyKitClient.LogicalHandler:Information: End processing HTTP request after 92.4618ms - OK
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 407907.3611ms 200 text/event-stream; charset=utf-8

.
.
.

Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request.

System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at ProxyKit.ProxyMiddleware.CopyProxyHttpResponse(HttpContext context, HttpResponseMessage responseMessage) in C:\Users\Jussi\Documents\GitHub\cNeuro\src\ProxyKit\ProxyMiddleware.cs:line 55
   at ProxyKit.ProxyMiddleware.Invoke(HttpContext context) in C:\Users\Jussi\Documents\GitHub\cNeuro\src\ProxyKit\ProxyMiddleware.cs:line 26
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Warning: The response has already started, the error page middleware will not be executed.
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer:Error: Connection ID "18086456105130524772", Request ID "80000065-0000-fb00-b63f-84710c7967bb": An unhandled exception was thrown by the application.

System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at ProxyKit.ProxyMiddleware.CopyProxyHttpResponse(HttpContext context, HttpResponseMessage responseMessage) in C:\Users\Jussi\Documents\GitHub\cNeuro\src\ProxyKit\ProxyMiddleware.cs:line 55
   at ProxyKit.ProxyMiddleware.Invoke(HttpContext context) in C:\Users\Jussi\Documents\GitHub\cNeuro\src\ProxyKit\ProxyMiddleware.cs:line 26
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 29710.8822ms 200 text/event-stream; charset=utf-8
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 34543.7289ms 200 text/event-stream; charset=utf-8
```
Hot updates to code do not flow to the client. To reproduce, you need a webpack application with HMR enabled and a simple Proxy with just:
```
app.RunProxy(
    context => context
         .ForwardTo("http://localhost:54469/")
         .AddXForwardedHeaders()
         .Send());
```
When accessing the application through its own port, HMR works as intended. Logs show no exceptions, only this one request and any subsequent hot updates:
```
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:54469/dist/__webpack_hmr  
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 30571.8054ms 200 text/event-stream; charset=utf-8
```
I can provide a minimal reproducible, if needed.

**Comment by damianh** [comment] 2019-02-06 12:57
Could you kindly put together a repro in a public repo? Something I can run easily. It would be very helpful in getting me to the bottom of this.

**Comment by jussimattila** [comment] 2019-02-06 13:24
Sure, I'll do that later today!

**Comment by jussimattila** [comment] 2019-02-06 19:59
I created a reproducible at https://github.com/jussimattila/ProxyKitIssue60Repro. While doing this, I did some cleaning of the project and what do you know, removing `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>` from the proxy project fixed this issue. Still, that is the default setting for new AspNetCore projects so if you'd like to have a look, the repro includes both a failing and working proxy.

**Comment by damianh** [comment] 2019-02-08 09:00
Thank you! Reproducible projects really helps 👍 

> `AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>`

Interesting catch there; will need to investigate that.

Hope to take a look this weekend. It sounds like you are unblocked for now?

**Comment by nicstrong** [comment] 2019-02-11 05:03
Also get a similar stack trace on a app running on IIS with InProcess model. In this case the upstream server is also my code and the AspNetCore logs for that app don't show any issue. It tends to show up under moderate load (approx 10 request coming in for that upstream server withing 100ms). Maybe it is something to do with the HttpClient and concurrency. Are they being allocated through HttpClientFactory?

`2019-02-11 15:22:56.585 +13:00 [ERR] Connection ID "18014402909139131753", Request ID "80005d6c-0400-fa00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at ProxyKit.ProxyMiddleware.CopyProxyHttpResponse(HttpContext context, HttpResponseMessage responseMessage)
   at ProxyKit.ProxyMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()`

**Comment by damianh** [comment] 2019-02-11 16:22
Having to do `AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>` is not optimal as `InProcess` is considered better performing. I definitely do not want to be recommending that.

Yes HttpClients are allocated through `HttpClientFactory`. I have a sneaking suspicion that there is a lifecycle thing here that is killing long running no-traffic connections.

Didn't get a chance to explore this weekend, it will have to be during the week.

**Comment by jussimattila** [comment] 2019-02-13 07:49
> Hope to take a look this weekend. It sounds like you are unblocked for now?

Sorry for the delayed reply! Yes, I'm unblocked now since in-process IIS hosting is not a requirement for us now during this evaluation.

**Comment by damianh** [comment] 2019-02-14 08:17
Well that is both a good and bad thing to hear :|

If you are really sure about this, please close this issue. If you are not sure, can leave it open for a bit...

**Closed** 2019-03-06 08:43 UTC

**Comment by jussimattila** [comment] 2019-03-08 07:07
Sorry that I missed the notification about your reply earlier! But yeah, it was okay to close this. Everything works fine without in-process hosting, and the problem is not related to ProxyKit. Also, in-process hosting is still an option in production, since it was only the dev-time HMR functionality that wasn't working for me. Thanks for a great library once more, we will use it for our upcoming project!
